language: go

go:
  - 1.8

install:
  - make deps

before_script:
  - mkdir -p $GOPATH/src/github.com/alexandrecarlton
  - ln -s $PWD $GOPATH/src/github.com/alexandrecarlton/gogurt

script:
  - make install
  - bats tests
