language: go

go:
  - 1.8

install:
  - make deps

before_script:
  - mkdir -p $GOPATH/src/github.com/alexandrecarlton
  - ln -s $PWD $GOPATH/src/github.com/alexandrecarlton/gogurt

script:
  - make install
  - gogurt gcc

# Purely to debug.
after_script:
  - ls ~/.gogurt/build/gcc/7.1.0
  - file ~/.gogurt/build/gcc/7.1.0/configure
